openapi: 3.0.3
servers: 
    - url: "https://dev.to" 
info: 
    title: StressWatch3 V1
    version: 1.0.0     
paths:
    /medias:
        $ref: "paths/medias.yaml"
    /schools:
        $ref: "paths/schools.yaml"
    /schools/{id}:
        $ref: "paths/schools@{id}.yaml"
    /schools/{id}/teachers:
        $ref: "paths/schools@{id}@teachers.yaml"
components:
    securitySchemes: 
        access_token:
            description: Get access token with POST /login.
            type: http
            scheme: bearer
            bearerFormat: JWT
